#!/bin/bash

BINDIR=/home/ffffe/bin
SRCDRIVE=fdrive-smb
DSTDRIVE=fdrive-work
ALLLOGFILE=/mnt/fdrive-work/Dropbox/bin/backuptower/log/all-rsync.txt
WORKLOGFILE=/mnt/fdrive-work/Dropbox/bin/backuptower/log/backup-rsync.txt

bash $BINDIR/mount-fdrive
if [ "$(ls -A /mnt/fdrive-work)" ]
then
:
else
        echo "fdrive-work not exist"  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo "`date +%Y%m%d%k%M%S` umount fdrive-work" | tee -a  $ALLLOGFILE $WORKLOGFILE
        umount /mnt/fdrive-work
        exit 1
fi
echo "--------$SRCDRIVE-rsync start--------" | tee -a  $ALLLOGFILE $WORKLOGFILE


if [ "$(ls -A /mnt/$SRCDRIVE)" ]
then
:
else
        echo "$SRCDRIVE not exist"  | tee -a  $ALLLOGFILE $WORKLOGFILE
	echo "`date +%Y%m%d%k%M%S` umount fdrive-work" | tee -a  $ALLLOGFILE $WORKLOGFILE
	umount /mnt/fdrive-work
        exit 1
fi


if [ "$(ls -A /mnt/$DSTDRIVE)" ]
then
:
else
        echo "$DSTDRIVE not exist" | tee -a  $ALLLOGFILE $WORKLOGFILE
	echo "`date +%Y%m%d%k%M%S` umount fdrive-work" | tee -a  $ALLLOGFILE $WORKLOGFILE
	umount /mnt/$SRCDRIVE
        exit 1
fi


echo "`date +%Y%m%d%k%M%S` rsync from $SRCDRIVE to $DSTDRIVE start"  | tee -a  $ALLLOGFILE $WORKLOGFILE
rsync
chown ffffe:ffffe -R /mnt/$DSTDRIVE
echo "`date +%Y%m%d%k%M%S` rsync finish"  | tee -a  $ALLLOGFILE $WORKLOGFILE


echo "`date +%Y%m%d%k%M%S` umount fdrive-work" | tee -a  $ALLLOGFILE $WORKLOGFILE
echo "--------$SRCDRIVE-rsync finish--------" | tee -a  $ALLLOGFILE $WORKLOGFILE
umount /mnt/fdrive-work
exit 0
