#!/bin/bash

#sudo mount -t cifs -o credentials=/etc/samba/sambapasswdworkingtower,uid=ffffe,gid=ffffe,mode=755 //pc/fdrive-work /mnt/fdrive-work
sudo mount -t cifs -o credentials=/etc/samba/sambapasswdworkingtower,uid=ffffe,gid=ffffe //pc/fdrive-work /mnt/fdrive-work

