#!/bin/bash

BINDIR=/home/ffffe/bin
SRCDRIVE=fdrive-work
DSTDRIVE=fdrive-smb
ALLLOGFILE=/mnt/fdrive-work/Dropbox/bin/backuptower/log/all-rsync.txt
WORKLOGFILE=/mnt/fdrive-work/Dropbox/bin/backuptower/log/rsync-all.txt

export PATH=$PATH:$BINDIR

if ! checkreachable pc > /dev/null 2>&1;then
	exit 0
fi

bash $BINDIR/mount-fdrive
if [ "$(ls -A /mnt/fdrive-work)" ]
then
:
else
        echo ""  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo ""  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo "fdrive-work not exist"  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo "`date +%Y%m%d-%H%M%S` umount fdrive-work" | tee -a  $ALLLOGFILE $WO
        echo ""  | tee -a  $ALLLOGFILE $WORKLOGFILE
RKLOGFILE
        umount /mnt/fdrive-work
        exit 1
fi

if [ "$(ls -A /mnt/fdrive-smb)" ]
then
:
else
        echo "!!!fdrive-smb not exist!!!"  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo "`date +%Y%m%d-%H%M%S` mount fdrive-smb" | tee -a  $ALLLOGFILE $WO
RKLOGFILE
        mount -a /dev/md0 /fdrive-smb
	if [ "$(ls -A /mnt/fdrive-smb)" ];then
        	echo "!!!cannot mount fdrive-smb!!!"  | tee -a  $ALLLOGFILE $WORKLOGFILE
	fi
fi

echo "" | tee -a  $ALLLOGFILE $WORKLOGFILE
echo "" | tee -a  $ALLLOGFILE $WORKLOGFILE
echo "----`date +%Y%m%d-%H%M%S`-rsync-all start----" | tee -a  $ALLLOGFILE $WORKLOGFILE
umount /mnt/fdrive-work

bash $BINDIR/systemBackup
bash $BINDIR/fdrive-rsync
bash $BINDIR/fmobile-rsync
bash $BINDIR/gdrive-rsync
bash $BINDIR/hdrive-rsync

bash $BINDIR/mount-fdrive
if [ "$(ls -A /mnt/fdrive-work)" ]
then
:
else
        echo ""  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo "fdrive-work not exist"  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo "`date +%Y%m%d-%H%M%S` umount fdrive-work" | tee -a  $ALLLOGFILE $WO
        echo ""  | tee -a  $ALLLOGFILE $WORKLOGFILE
RKLOGFILE
        umount /mnt/fdrive-work
        exit 1
fi

if [ "$(ls -A /mnt/fdrive-smb)" ]
then
:
else
        echo "!!!fdrive-smb not exist!!!"  | tee -a  $ALLLOGFILE $WORKLOGFILE
        echo "`date +%Y%m%d-%H%M%S` mount fdrive-smb" | tee -a  $ALLLOGFILE $WORKLOGFILE
        mount -a /dev/md0 /fdrive-smb
fi


echo "`date +%Y%m%d-%H%M%S` umount fdrive-work" | tee -a  $ALLLOGFILE $WORKLOGFILE
echo "----`date +%Y%m%d-%H%M%S`-rsync-all finish----" | tee -a  $ALLLOGFILE $WORKLOGFILE
echo "" | tee -a  $ALLLOGFILE $WORKLOGFILE
umount /mnt/fdrive-work
exit 0

